apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: mnist-workflow
spec:
  entrypoint: mnist-workflow-preprocess-train-deploy
  volumes:
  - name: git-private-key
    secret:
      secretName: git-secret-ssh
  templates:
  - name: mnist-workflow-preprocess-train-deploy
    steps:
    - - name: pre-process            # pre-process is run before the following steps
        template: mnist-preprocess
    - - name: train-original           # train-original is run after pre-process and at same time with train-preprocessed step
        template: mnist-train-original
      - name: train-preprocessed           # train-preprocessed is run before the following steps and at the time with train-original
        template: mnist-train-preprocessed
    - - name: retrieve-best-model           # retrieve-best-model is run before the following steps and after training steps
        template: mlflow-mnist-best-model
    - - name: deploy-model           # deploy-model is run after the retrieve-best-model step and only if retrieve-best-model have tf result
        template: mnist-deploy-tf-serving
        when: "{{steps.retrieve-best-model.outputs.parameters.model-flavor}} == tf"
        arguments:
          parameters:
            - name: predictor
              value: "tensorflow"
            - name: model-uri
              value: "{{steps.retrieve-best-model.outputs.parameters.model-uri}}"








  - name: mnist-preprocess
    inputs:
      artifacts:
      - name: repo-source
        path: /app
        git:
          repo: https://github.com/safoinme/Mnist-MLFlow-dvc-Argo.git
          revision: "argo"
    container:
      image: ouassine/kadm:0.1.0
      volumeMounts:
        - name: git-private-key
          mountPath: "/secret/mountpath"
      env:
          - name: COMMIT_USER
            valueFrom:
              secretKeyRef:
                name: git-credentials
                key: GIT_USERNAME
          - name: COMMIT_EMAIL
            valueFrom:
              secretKeyRef:
                name: git-credentials
                key: GIT_MAIL
          - name: DVC_BUCKET
            valueFrom:
              secretKeyRef:
                name: dvc-access
                key: DVC_BUCKET
          - name: DVC_S3_ENDPOINT_URL
            valueFrom:
              secretKeyRef:
                name: dvc-access
                key: DVC_S3_ENDPOINT_URL
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: dvc-access
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: dvc-access
                key: AWS_SECRET_ACCESS_KEY
          - name: GIT_REPO
            value: git@github.com:safoinme/Mnist-MLFlow-dvc-Argo.git
          - name: GIT_BRANCH
            value: "argo"
      command: [sh, -c]
      args: 
        - ./config_git.sh;
          python3 pre-process.py;
          ./save_changes.sh
      workingDir: /app
  - name: mnist-train-original 
    inputs:
      artifacts:
      - name: repo-source
        path: /app
        git:
          repo: https://github.com/safoinme/Mnist-MLFlow-dvc-Argo.git
          revision: "argo"
    container:
      image: ouassine/kadm:0.1.0
      volumeMounts:
        - name: git-private-key
          mountPath: "/secret/mountpath"
      env:
          - name: COMMIT_USER
            valueFrom:
              secretKeyRef:
                name: git-credentials
                key: GIT_USERNAME
          - name: COMMIT_EMAIL
            valueFrom:
              secretKeyRef:
                name: git-credentials
                key: GIT_MAIL
          - name: MLFLOW_TRACKING_URI
            valueFrom:
              secretKeyRef:
                name: mlflow-access
                key: MLFLOW_TRACKING_URI
          - name: MLFLOW_S3_ENDPOINT_URL
            valueFrom:
              secretKeyRef:
                name: mlflow-access
                key: MLFLOW_S3_ENDPOINT_URL
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: mlflow-access
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: mlflow-access
                key: AWS_SECRET_ACCESS_KEY
          - name: DVC_BUCKET
            valueFrom:
              secretKeyRef:
                name: dvc-access
                key: DVC_BUCKET
          - name: DVC_S3_ENDPOINT_URL
            valueFrom:
              secretKeyRef:
                name: dvc-access
                key: DVC_S3_ENDPOINT_URL
          - name: GIT_REPO
            value: git@github.com:safoinme/Mnist-MLFlow-dvc-Argo.git
          - name: GIT_BRANCH
            value: "argo"
      command: [sh, -c]
      args: 
        - ./config_git.sh;
          python3 train.py
      workingDir: /app
  - name: mnist-train-preprocessed
    inputs:
      artifacts:
      - name: repo-source
        path: /app
        git:
          repo: https://github.com/safoinme/Mnist-MLFlow-dvc-Argo.git
          revision: "argo"
    container:
      image: ouassine/kadm:0.1.0
      volumeMounts:
        - name: git-private-key
          mountPath: "/secret/mountpath"
      env:
          - name: COMMIT_USER
            valueFrom:
              secretKeyRef:
                name: git-credentials
                key: GIT_USERNAME
          - name: COMMIT_EMAIL
            valueFrom:
              secretKeyRef:
                name: git-credentials
                key: GIT_MAIL
          - name: MLFLOW_TRACKING_URI
            valueFrom:
              secretKeyRef:
                name: mlflow-access
                key: MLFLOW_TRACKING_URI
          - name: MLFLOW_S3_ENDPOINT_URL
            valueFrom:
              secretKeyRef:
                name: mlflow-access
                key: MLFLOW_S3_ENDPOINT_URL
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: mlflow-access
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: mlflow-access
                key: AWS_SECRET_ACCESS_KEY
          - name: DVC_BUCKET
            valueFrom:
              secretKeyRef:
                name: dvc-access
                key: DVC_BUCKET
          - name: DVC_S3_ENDPOINT_URL
            valueFrom:
              secretKeyRef:
                name: dvc-access
                key: DVC_S3_ENDPOINT_URL
          - name: GIT_REPO
            value: git@github.com:safoinme/Mnist-MLFlow-dvc-Argo.git
          - name: GIT_BRANCH
            value: "argo"
      command: [sh, -c]
      args: 
        - ./config_git.sh;
          python3 train-preprocess.py
      workingDir: /app
  - name: mlflow-mnist-best-model
    inputs:
      artifacts:
      - name: repo-source
        path: /app
        git:
          repo: https://github.com/safoinme/Mnist-MLFlow-dvc-Argo.git
          revision: "argo"
    container:
      image: safoinme/python-mlflow-expirements:0.1.0
      env:
          - name: MLFLOW_TRACKING_URI
            valueFrom:
              secretKeyRef:
                name: mlflow-access
                key: MLFLOW_TRACKING_URI
          - name: MLFLOW_S3_ENDPOINT_URL
            valueFrom:
              secretKeyRef:
                name: mlflow-access
                key: MLFLOW_S3_ENDPOINT_URL
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: mlflow-access
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: mlflow-access
                key: AWS_SECRET_ACCESS_KEY
      command: [sh, -c]
      args: 
        - python3 experiment_comparaison.py;      
      workingDir: /app
    outputs:
      parameters:
        - name: model-flavor
          valueFrom:
            path: /tmp/artifact_downloads/model/data/save_format.txt
        - name: model-uri
          valueFrom:
            path: /tmp/best_model_artifact_uri.txt
  #- name: mnist-deploy-tf-serving
  #  inputs:
  #    parameters:
  #    - name: model-uri
  #  container:
  #    image: safoinme/python-mlflow-expirements:0.1.0
  #    command: [sh, -c]
  #    args: ["echo {{inputs.parameters.model-uri}} "]  
  
  - name: mnist-deploy-tf-serving
    inputs:
      parameters:
      - name: model-uri
      - name: predictor
    resource:
      action: create
      manifest: |
        apiVersion: "serving.kserve.io/v1beta1"
        kind: "InferenceService"
        metadata:
          name: "mnist-example-s3"
        spec:
          predictor:
            serviceAccountName: stminio
            {{inputs.parameters.predictor}}:
              storageUri: "{{inputs.parameters.model-uri}}"
              resources:
                limits:
                  memory: 2Gi
                  cpu: "1"
  #- name: mnist-deploy-tf-serving
  #  resource:
  #    action: create
      # successCondition and failureCondition are optional expressions which are
      # evaluated upon every update of the resource. If failureCondition is ever
      # evaluated to true, the step is considered failed. Likewise, if successCondition
      # is ever evaluated to true the step is considered successful. It uses kubernetes
      # label selection syntax and can be applied against any field of the resource
      # (not just labels). Multiple AND conditions can be represented by comma
      # delimited expressions. For more details, see:
      # https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
  #    successCondition: status.succeeded > 0
  #    failureCondition: status.failed > 3
  #    manifest: |
  #      apiVersion: apps/v1
  #      kind: Deployment
  #      metadata:
  #        name: tf-serving-deployment
  #      spec:
  #        replicas: 1
  #        template:
  #          metadata:
  #            labels:
  #              app: tf-serving-server
  #          spec:
  #            containers:
  #            - name: tf-serving-container
  #              image: tensorflow/serving:latest
  #              ports:
  #              - containerPort: 8500
  #      ---
  #      apiVersion: v1
  #      kind: Service
  #      metadata:
  #        labels:
  #          run: tf-serving-service
  #        name: tf-serving-service
  #      spec:
  #        ports:
  #        - port: 8500
  #          targetPort: 8500